# -*- coding: utf-8 -*-
"""api_sentences.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOkDpo8H1W6EsSh1_jbSMNRzcdcGiHK2
"""

warrantly_listing = ['what all warranties are available', 'list all warranties', 'warranties list', 'I want all warranties', 'all warranties']
warranty_details = ['tell me my warranty details', 'give me my warranty details', 'warranty details', 'I want my warranty info', 'information regarding my warranty']
kit_details = ['give me my warranty kit details', 'information regarding my warranty kit', 'warranty kit', 'my warranty kit']
register_claim = ['please register claim', 'claim registration', 'register claim', 'I want to register a claim', 'registering new claim']
media_upload = ['upload media', 'upload a file', 'file uploading', 'please upload my file', 'submit a media file']
media_download = ['I want to get my file', 'download my file', 'file downloading', 'please download a file for me', 'extract media file']
warranty_creation = ['create a new warranty', 'i want to create new warranty', 'new warranty', 'new warranty creation', 'please form a warranty for me']
